name: my-first-workflow
# To get a trigger on every push in this repo on any branch
on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: Running a single command in Job1
        run: echo "Hi, this is my first GitHub workflow"
      - name: Checking OS release for GitHub Hosted Runner
        run: cat /etc/os-release
